// Generator: rewrite login.vue (dark holo theme + SplatTruck)
// Chinese copy is extracted from existing files at runtime (never typed here)
const fs = require('fs');
const root = 'D:/code/work-space-agent/dst-v2x-agent/frontend';
const oldLogin = fs.readFileSync(root + '/pages/login.vue', 'utf8');
const hero = fs.readFileSync(root + '/components/landing/HeroSection.vue', 'utf8');
const refHtml = fs.readFileSync('E:/dst_agent_car/index (7).html', 'utf8');

function pick(re, src, name) {
  const m = src.match(re);
  if (!m) throw new Error('extract failed: ' + name);
  return m[1];
}
// old login form strings
const brandTitle = pick(/brandTitle: '([^']*)'/, oldLogin, 'brandTitle');
const welcome = pick(/welcome: '([^']*)'/, oldLogin, 'welcome');
const sub = pick(/sub: '([^']*)'/, oldLogin, 'sub');
const account = pick(/account: '([^']*)'/, oldLogin, 'account');
const passwordPh = pick(/password: '([^']*)'/, oldLogin, 'password');
const remember = pick(/remember: '([^']*)'/, oldLogin, 'remember');
const forgot = pick(/forgot: '([^']*)'/, oldLogin, 'forgot');
const loginBtn = pick(/login: '([^']*)'/, oldLogin, 'login');
const orNote = pick(/orNote: '([^']*)'/, oldLogin, 'orNote');
const verifying = pick(/stageText\.value = '([^']*)'/, oldLogin, 'verifying');
const badCred = pick(/res\.message \|\| '([^']*)'/, oldLogin, 'badCred');
const netErr = pick(/catch \(e\) \{\s*error\.value = '([^']*)'/, oldLogin, 'netErr');
const navComment = (() => {
  const lines = oldLogin.split('\n');
  const i = lines.findIndex(l => l.includes("navigateTo('/transition')"));
  if (i < 1) throw new Error('nav comment missing');
  return lines[i - 1].trim();
})();
// hero copy from landing HeroSection
const heroTitle1 = pick(/<h1>([^<]+)<br>([^<]+)<\/h1>/, hero, 'hero1');
const heroTitle2 = pick(/<h1>[^<]+<br>([^<]+)<\/h1>/, hero, 'hero2');
const heroSub = pick(/<p class="sub">([^<]+)<\/p>/, hero, 'heroSub');
// hint strings from reference html
function hintText(n) {
  const lines = refHtml.split('\n');
  const i = lines.findIndex(l => l.includes('<div class="hint mono">'));
  if (i < 0) throw new Error('hint block missing');
  return lines[i + n].replace(/<[^>]+>/g, '').trim();
}
const hint1 = hintText(1);
const hint2 = hintText(2);
// splat word for page comment (from reference <title>)
const splatWord = pick(/<title>([^<]+)<\/title>/, refHtml, 'title').split('\u00b7')[1].trim();

console.log('extracted:', JSON.stringify({ brandTitle, welcome, heroTitle1, heroTitle2, hint1, hint2, splatWord, navComment }, null, 1));

const out = [];
out.push('<template>');
out.push('  <!-- login page: dark holo theme, ' + splatWord + ' truck (SplatTruck) + glass form -->');
out.push('  <main class="login-page">');
out.push('    <div class="bg"></div>');
out.push('    <div class="scanline"></div>');
out.push('    <ClientOnly><SplatTruck :shift-x="-0.16" :shift-y="0.02" :size="1.3" :depth="0" :drift="0" :auto-spin="false" /></ClientOnly>');
out.push('');
out.push('    <header class="top">');
out.push('      <div class="brand">');
out.push('        <div class="logo">DST</div>');
out.push('        <div>');
out.push('          <div class="brand-title">{{ t.brandTitle }}</div>');
out.push('          <div class="brand-sub">DST IOT INTELLIGENT PLATFORM</div>');
out.push('        </div>');
out.push('      </div>');
out.push('      <div class="top-tag mono">GAUSSIAN SPLAT &middot; HOLO DECK</div>');
out.push('    </header>');
out.push('');
out.push('    <section class="form-side">');
out.push('      <form class="login" @submit.prevent="onSubmit">');
out.push('        <svg class="card-shield" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M12 3 5 6v5c0 4.6 2.9 8 7 10 4.1-2 7-5.4 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-4"/></svg>');
out.push('        <h2>{{ t.welcome }}</h2>');
out.push('        <p class="sub">{{ t.sub }}</p>');
out.push('        <p class="platform-tag">INTELLIGENT MOBILITY PLATFORM</p>');
out.push('        <label class="field">');
out.push('          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><circle cx="12" cy="8" r="4"/><path d="M5 21v-2a7 7 0 0 1 14 0v2"/></svg>');
out.push('          <input v-model.trim="username" aria-label="account" :placeholder="t.account" autocomplete="username" />');
out.push('        </label>');
out.push('        <label class="field">');
out.push('          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg>');
out.push('          <input v-model="password" :type="showPwd ? \'text\' : \'password\'" aria-label="password" :placeholder="t.password" autocomplete="current-password" />');
out.push('          <button class="eye" type="button" :aria-label="showPwd ? \'hide\' : \'show\'" @click="showPwd = !showPwd"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" style="width:18px;height:18px"><path d="M2 12s3.5-6.5 10-6.5S22 12 22 12s-3.5 6.5-10 6.5S2 12 22 12z"/><circle cx="12" cy="12" r="2.5"/></svg></button>');
out.push('        </label>');
out.push('        <div class="row">');
out.push('          <label class="check"><input v-model="remember" type="checkbox" />{{ t.remember }}</label>');
out.push('          <a class="link" href="#" @click.prevent>{{ t.forgot }}</a>');
out.push('        </div>');
out.push('        <p v-if="error" class="err">{{ error }}</p>');
out.push('        <button class="submit" type="submit" :disabled="loading">{{ loading ? stageText : t.login }}<span class="btn-arrow" aria-hidden="true">&#8594;</span></button>');
out.push('        <div class="or">{{ t.orNote }}</div>');
out.push('        <div class="signup">admin / admin123 &middot; op1 / op123456</div>');
out.push('      </form>');
out.push('    </section>');
out.push('');
out.push('    <div class="hero-copy">');
out.push('      <h1>' + heroTitle1 + '<br><em>' + heroTitle2 + '</em></h1>');
out.push('      <p>{{ t.heroDesc }}</p>');
out.push('    </div>');
out.push('');
out.push('    <div class="hint mono">');
out.push('      <span><i></i>{{ t.hint1 }}</span>');
out.push('      <span><i></i>{{ t.hint2 }}</span>');
out.push('    </div>');
out.push('');
out.push('    <span class="corner-tag mono">DST IOT INTELLIGENT PLATFORM</span>');
out.push('  </main>');
out.push('</template>');
out.push('');
out.push('<script setup>');
out.push("definePageMeta({ layout: false })");
out.push('');
out.push("const { login } = useAuth()");
out.push("const username = ref('admin')");
out.push("const password = ref('admin123')");
out.push('const remember = ref(true)');
out.push('const showPwd = ref(false)');
out.push('const loading = ref(false)');
out.push("const stageText = ref('')");
out.push("const error = ref('')");
out.push('');
out.push('const t = {');
out.push("  brandTitle: '" + brandTitle + "',");
out.push("  welcome: '" + welcome + "',");
out.push("  sub: '" + sub + "',");
out.push("  account: '" + account + "',");
out.push("  password: '" + passwordPh + "',");
out.push("  remember: '" + remember + "',");
out.push("  forgot: '" + forgot + "',");
out.push("  login: '" + loginBtn + "',");
out.push("  orNote: '" + orNote + "',");
out.push("  heroDesc: '" + heroSub + "',");
out.push("  hint1: '" + hint1 + "',");
out.push("  hint2: '" + hint2 + "'");
out.push('}');
out.push('');
out.push('async function onSubmit() {');
out.push('  if (!username.value || !password.value || loading.value) return');
out.push('  loading.value = true');
out.push("  error.value = ''");
out.push("  stageText.value = '" + verifying + "'");
out.push('  try {');
out.push('    const res = await login(username.value, password.value)');
out.push('    if (res.ok) {');
out.push('      ' + navComment);
out.push("      navigateTo('/transition')");
out.push('    } else {');
out.push("      error.value = res.message || '" + badCred + "'");
out.push('    }');
out.push('  } catch (e) {');
out.push("    error.value = '" + netErr + "'");
out.push('  } finally {');
out.push('    loading.value = false');
out.push('  }');
out.push('}');
out.push('</' + 'script>');
out.push('');
out.push('<style scoped>');
out.push('.login-page {');
out.push('  position: fixed; inset: 0; overflow: hidden;');
out.push('  background: #021316; color: #d3fffe;');
out.push('}');
out.push('');
out.push('/* deep background glow + grid */');
out.push('.bg {');
out.push('  position: absolute; inset: 0; z-index: 0;');
out.push('  background:');
out.push('    radial-gradient(130% 100% at 42% 42%, rgba(6, 51, 58, 0.9) 0%, rgba(3, 32, 37, 0.6) 46%, rgba(2, 19, 22, 0) 100%),');
out.push('    radial-gradient(720px 420px at 82% 30%, rgba(64, 232, 220, 0.07), transparent 65%);');
out.push('}');
out.push('.bg::after {');
out.push("  content: ''; position: absolute; inset: 0;");
out.push('  background-image:');
out.push('    linear-gradient(rgba(64, 232, 220, 0.045) 1px, transparent 1px),');
out.push('    linear-gradient(90deg, rgba(64, 232, 220, 0.045) 1px, transparent 1px);');
out.push('  background-size: 56px 56px;');
out.push('  mask-image: radial-gradient(90% 90% at 50% 50%, #000 30%, transparent 100%);');
out.push('  -webkit-mask-image: radial-gradient(90% 90% at 50% 50%, #000 30%, transparent 100%);');
out.push('}');
out.push('');
out.push('/* HUD scanline */');
out.push('.scanline {');
out.push('  position: absolute; left: 0; right: 0; top: -12%;');
out.push('  height: 12%; z-index: 2; pointer-events: none;');
out.push('  background: linear-gradient(to bottom,');
out.push('    transparent 0%, rgba(64, 232, 220, 0.05) 70%,');
out.push('    rgba(64, 232, 220, 0.14) 96%, rgba(211, 255, 254, 0.30) 100%);');
out.push('  mix-blend-mode: screen;');
out.push('  animation: sweep 7s cubic-bezier(.45, 0, .55, 1) infinite;');
out.push('}');
out.push('@keyframes sweep {');
out.push('  0% { transform: translateY(0); }');
out.push('  55% { transform: translateY(1020%); }');
out.push('  100% { transform: translateY(1020%); }');
out.push('}');
out.push('');
out.push('.mono {');
out.push('  font-family: ui-monospace, "SF Mono", "JetBrains Mono", Menlo, Consolas, monospace;');
out.push('  font-feature-settings: "tnum";');
out.push('}');
out.push('');
out.push('/* header */');
out.push('.top {');
out.push('  position: absolute; top: 0; left: 0; right: 0; z-index: 6;');
out.push('  display: flex; align-items: center; justify-content: space-between;');
out.push('  padding: 22px 36px;');
out.push('}');
out.push('.brand { display: flex; align-items: center; gap: 12px; }');
out.push('.logo {');
out.push('  font-size: 26px; font-weight: 800; font-style: italic; letter-spacing: 1px;');
out.push('  background: linear-gradient(135deg, #40e8dc, #adefed);');
out.push('  -webkit-background-clip: text; background-clip: text; color: transparent;');
out.push('}');
out.push('.brand-title { font-size: 15px; font-weight: 700; color: #d3fffe; }');
out.push('.brand-sub { font-size: 10px; letter-spacing: 2px; color: rgba(127, 201, 198, 0.55); }');
out.push('.top-tag {');
out.push('  font-size: 10px; letter-spacing: 0.18em; color: #7fc9c6;');
out.push('  padding: 7px 12px; border: 1px solid rgba(64, 232, 220, 0.22); border-radius: 4px;');
out.push('  background: rgba(3, 30, 34, 0.5);');
out.push('}');
out.push('');
out.push('/* glass form */');
out.push('.form-side {');
out.push('  position: absolute; right: 4.5%; top: 50%; transform: translateY(-50%); z-index: 5;');
out.push('  width: min(400px, 92vw);');
out.push('  display: flex; align-items: center; justify-content: center;');
out.push('}');
out.push('.login {');
out.push('  width: 100%; padding: 38px 34px 30px;');
out.push('  background: rgba(3, 30, 34, 0.62);');
out.push('  backdrop-filter: blur(16px) saturate(1.3);');
out.push('  -webkit-backdrop-filter: blur(16px) saturate(1.3);');
out.push('  border: 1px solid rgba(64, 232, 220, 0.18); border-radius: 18px;');
out.push('  box-shadow: 0 0 0 1px rgba(2, 19, 22, 0.6), 0 18px 50px rgba(0, 0, 0, 0.45),');
out.push('              inset 0 1px 0 rgba(211, 255, 254, 0.08);');
out.push('  text-align: center;');
out.push('}');
out.push('.card-shield { width: 40px; height: 40px; color: #40e8dc; margin-bottom: 10px; }');
out.push('.login h2 { margin: 0; font-size: 24px; font-weight: 800; color: #d3fffe; }');
out.push('.login .sub { margin: 8px 0 2px; font-size: 13px; color: rgba(127, 201, 198, 0.75); }');
out.push('.platform-tag { margin: 0 0 22px; font-size: 10px; letter-spacing: 2.5px; color: rgba(127, 201, 198, 0.45); }');
out.push('');
out.push('.field {');
out.push('  display: flex; align-items: center; gap: 10px;');
out.push('  margin-bottom: 14px; padding: 0 14px; height: 46px;');
out.push('  background: rgba(2, 19, 22, 0.55);');
out.push('  border: 1px solid rgba(64, 232, 220, 0.16); border-radius: 10px;');
out.push('  transition: border-color .15s ease, box-shadow .15s ease;');
out.push('}');
out.push('.field:focus-within { border-color: #40e8dc; box-shadow: 0 0 0 3px rgba(64, 232, 220, 0.14); }');
out.push('.field svg { width: 19px; height: 19px; color: rgba(127, 201, 198, 0.6); flex-shrink: 0; }');
out.push('.field input { flex: 1; border: none; outline: none; background: transparent; font-size: 14px; color: #d3fffe; }');
out.push('.field input::placeholder { color: rgba(127, 201, 198, 0.4); }');
out.push('.eye { border: none; background: none; cursor: pointer; color: rgba(127, 201, 198, 0.6); padding: 2px; }');
out.push('');
out.push('.row {');
out.push('  display: flex; align-items: center; justify-content: space-between;');
out.push('  margin: 4px 2px 16px; font-size: 12px; color: rgba(127, 201, 198, 0.75);');
out.push('}');
out.push('.check { display: flex; align-items: center; gap: 6px; cursor: pointer; }');
out.push('.check input { accent-color: #40e8dc; }');
out.push('.link { color: #40e8dc; text-decoration: none; }');
out.push('');
out.push('.err {');
out.push('  margin: 0 0 12px; padding: 8px 12px; font-size: 12px; text-align: left;');
out.push('  color: #ff9a8a; background: rgba(255, 106, 90, 0.1); border-radius: 8px;');
out.push('}');
out.push('');
out.push('.submit {');
out.push('  width: 100%; height: 46px; border: none; border-radius: 10px; cursor: pointer;');
out.push('  display: flex; align-items: center; justify-content: center; gap: 8px;');
out.push('  background: linear-gradient(135deg, #2a827e, #40e8dc); color: #021316;');
out.push('  font-size: 15px; font-weight: 700; letter-spacing: 2px;');
out.push('  box-shadow: 0 0 18px rgba(64, 232, 220, 0.3);');
out.push('  transition: transform .15s ease, box-shadow .15s ease, background .3s ease;');
out.push('}');
out.push('.submit:hover:not(:disabled) { background: linear-gradient(135deg, #34a29c, #adefed); box-shadow: 0 0 28px rgba(64, 232, 220, 0.55); transform: translateY(-1px); }');
out.push('.submit:disabled { opacity: 0.75; cursor: default; }');
out.push('.btn-arrow { font-size: 17px; letter-spacing: 0; }');
out.push('');
out.push('.or { margin: 18px 0 6px; font-size: 12px; color: rgba(127, 201, 198, 0.5); }');
out.push('.signup { font-size: 11px; color: rgba(127, 201, 198, 0.55); }');
out.push('');
out.push('/* hero copy */');
out.push('.hero-copy { position: absolute; left: 6%; bottom: 7%; z-index: 4; pointer-events: none; }');
out.push('.hero-copy h1 {');
out.push('  margin: 0; font-size: 40px; line-height: 1.28; font-weight: 800; color: #d3fffe;');
out.push('  text-shadow: 0 2px 24px rgba(2, 19, 22, 0.9);');
out.push('}');
out.push('.hero-copy h1 em { font-style: normal; color: #40e8dc; text-shadow: 0 0 24px rgba(64, 232, 220, 0.45); }');
out.push('.hero-copy p { margin: 12px 0 0; font-size: 14px; color: rgba(127, 201, 198, 0.8); max-width: 420px; }');
out.push('');
out.push('/* interaction hint */');
out.push('.hint {');
out.push('  position: absolute; left: 50%; bottom: 20px; transform: translateX(-50%); z-index: 6;');
out.push('  font-size: 11px; letter-spacing: 0.12em; color: #7fc9c6; pointer-events: none;');
out.push('  display: flex; gap: 1.8em; white-space: nowrap;');
out.push('}');
out.push('.hint i {');
out.push('  font-style: normal; display: inline-block;');
out.push('  width: 6px; height: 6px; border-radius: 50%;');
out.push('  background: #40e8dc; margin-right: 8px; vertical-align: 1px;');
out.push('  box-shadow: 0 0 6px #40e8dc;');
out.push('}');
out.push('');
out.push('.corner-tag {');
out.push('  position: absolute; right: 24px; bottom: 16px; z-index: 6;');
out.push('  font-size: 10px; letter-spacing: 3px; color: rgba(127, 201, 198, 0.45);');
out.push('}');
out.push('');
out.push('@media (max-width: 900px) {');
out.push('  .form-side { right: 50%; transform: translate(50%, -50%); }');
out.push('  .hero-copy { display: none; }');
out.push('  .hint { display: none; }');
out.push('  .top-tag { display: none; }');
out.push('}');
out.push('</style>');
out.push('');

const target = root + '/pages/login.vue';
fs.writeFileSync(target, out.join('\n'), 'utf8');
console.log('written', target, out.length, 'lines');
