// Restore login.vue to the original version (light water scene + static hero image)
const fs = require('fs');
const root = 'D:/code/work-space-agent/dst-v2x-agent/frontend';
const curLogin = fs.readFileSync(root + '/pages/login.vue', 'utf8');

function pick(re, src, name) {
  const m = src.match(re);
  if (!m) throw new Error('extract failed: ' + name);
  return m[1];
}
const brandTitle = pick(/brandTitle: '([^']*)'/, curLogin, 'brandTitle');
const welcome = pick(/welcome: '([^']*)'/, curLogin, 'welcome');
const sub = pick(/sub: '([^']*)'/, curLogin, 'sub');
const account = pick(/account: '([^']*)'/, curLogin, 'account');
const passwordPh = pick(/password: '([^']*)'/, curLogin, 'password');
const remember = pick(/remember: '([^']*)'/, curLogin, 'remember');
const forgot = pick(/forgot: '([^']*)'/, curLogin, 'forgot');
const loginBtn = pick(/login: '([^']*)'/, curLogin, 'login');
const orNote = pick(/orNote: '([^']*)'/, curLogin, 'orNote');
const verifying = pick(/stageText\.value = '([^']*)'/, curLogin, 'verifying');
const badCred = pick(/res\.message \|\| '([^']*)'/, curLogin, 'badCred');
const netErr = pick(/catch \(e\) \{\s*error\.value = '([^']*)'/, curLogin, 'netErr');
const navComment = (() => {
  const lines = curLogin.split('\n');
  const i = lines.findIndex(l => l.includes("navigateTo('/transition')"));
  if (i < 1) throw new Error('nav comment missing');
  return lines[i - 1].trim();
})();

const out = [];
out.push('<template>');
out.push('  <!-- login page: unified scene, hero image multiply-blended over water surface -->');
out.push('  <main class="login-page">');
out.push('    <div class="sky"></div>');
out.push('    <div class="beams"><i></i><i></i><i></i></div>');
out.push('');
out.push('    <div class="hero-wrap">');
out.push('      <img class="hero-img" src="/images/img_1.png" :alt="t.brandTitle" />');
out.push('      <img class="hero-reflect" src="/images/img_1.png" aria-hidden="true" />');
out.push('    </div>');
out.push('');
out.push('    <ClientOnly><WaterRipple /></ClientOnly>');
out.push('');
out.push('    <header class="top">');
out.push('      <div class="brand">');
out.push('        <div class="logo">DST</div>');
out.push('        <div>');
out.push('          <div class="brand-title">{{ t.brandTitle }}</div>');
out.push('          <div class="brand-sub">DST IOT INTELLIGENT PLATFORM</div>');
out.push('        </div>');
out.push('      </div>');
out.push('    </header>');
out.push('');
out.push('    <section class="form-side">');
out.push('      <form class="login" @submit.prevent="onSubmit">');
out.push('        <svg class="card-shield" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M12 3 5 6v5c0 4.6 2.9 8 7 10 4.1-2 7-5.4 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-4"/></svg>');
out.push('        <h2>{{ t.welcome }}</h2>');
out.push('        <p class="sub">{{ t.sub }}</p>');
out.push('        <p class="platform-tag">INTELLIGENT MOBILITY PLATFORM</p>');
out.push('        <label class="field">');
out.push('          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><circle cx="12" cy="8" r="4"/><path d="M5 21v-2a7 7 0 0 1 14 0v2"/></svg>');
out.push('          <input v-model.trim="username" aria-label="account" :placeholder="t.account" autocomplete="username" />');
out.push('        </label>');
out.push('        <label class="field">');
out.push('          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg>');
out.push('          <input v-model="password" :type="showPwd ? \'text\' : \'password\'" aria-label="password" :placeholder="t.password" autocomplete="current-password" />');
out.push('          <button class="eye" type="button" :aria-label="showPwd ? \'hide\' : \'show\'" @click="showPwd = !showPwd"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" style="width:18px;height:18px"><path d="M2 12s3.5-6.5 10-6.5S22 12 22 12s-3.5 6.5-10 6.5S2 12 22 12z"/><circle cx="12" cy="12" r="2.5"/></svg></button>');
out.push('        </label>');
out.push('        <div class="row">');
out.push('          <label class="check"><input v-model="remember" type="checkbox" />{{ t.remember }}</label>');
out.push('          <a class="link" href="#" @click.prevent>{{ t.forgot }}</a>');
out.push('        </div>');
out.push('        <p v-if="error" class="err">{{ error }}</p>');
out.push('        <button class="submit" type="submit" :disabled="loading">{{ loading ? stageText : t.login }}<span class="btn-arrow" aria-hidden="true">&#8594;</span></button>');
out.push('        <div class="or">{{ t.orNote }}</div>');
out.push('        <div class="signup">admin / admin123 &middot; op1 / op123456</div>');
out.push('      </form>');
out.push('    </section>');
out.push('');
out.push('    <div class="hero-copy">');
out.push('      <h1>AI <em>{{ t.heroEm }}</em><br>{{ t.heroLine2 }}</h1>');
out.push('      <p>{{ t.heroDesc }}</p>');
out.push('    </div>');
out.push('');
out.push('    <span class="corner-tag">DST IOT INTELLIGENT PLATFORM</span>');
out.push('  </main>');
out.push('</template>');
out.push('');
