// Generator v2: login.vue = original light scene (sky/beams/WaterRipple) + SplatTruck light theme
const fs = require('fs');
const root = 'D:/code/work-space-agent/dst-v2x-agent/frontend';
const curLogin = fs.readFileSync(root + '/pages/login.vue', 'utf8');
const hero = fs.readFileSync(root + '/components/landing/HeroSection.vue', 'utf8');
const refHtml = fs.readFileSync('E:/dst_agent_car/index (7).html', 'utf8');

function pick(re, src, name) {
  const m = src.match(re);
  if (!m) throw new Error('extract failed: ' + name);
  return m[1];
}
const brandTitle = pick(/brandTitle: '([^']*)'/, curLogin, 'brandTitle');
const welcome = pick(/welcome: '([^']*)'/, curLogin, 'welcome');
const sub = pick(/sub: '([^']*)'/, curLogin, 'sub');
const account = pick(/account: '([^']*)'/, curLogin, 'account');
const passwordPh = pick(/password: '([^']*)'/, curLogin, 'password');
const remember = pick(/remember: '([^']*)'/, curLogin, 'remember');
const forgot = pick(/forgot: '([^']*)'/, curLogin, 'forgot');
const loginBtn = pick(/login: '([^']*)'/, curLogin, 'login');
const orNote = pick(/orNote: '([^']*)'/, curLogin, 'orNote');
const verifying = pick(/stageText\.value = '([^']*)'/, curLogin, 'verifying');
const badCred = pick(/res\.message \|\| '([^']*)'/, curLogin, 'badCred');
const netErr = pick(/catch \(e\) \{\s*error\.value = '([^']*)'/, curLogin, 'netErr');
const navComment = (() => {
  const lines = curLogin.split('\n');
  const i = lines.findIndex(l => l.includes("navigateTo('/transition')"));
  if (i < 1) throw new Error('nav comment missing');
  return lines[i - 1].trim();
})();
const heroTitle1 = pick(/<h1>([^<]+)<br>([^<]+)<\/h1>/, hero, 'hero1');
const heroTitle2 = pick(/<h1>[^<]+<br>([^<]+)<\/h1>/, hero, 'hero2');
const heroSub = pick(/<p class="sub">([^<]+)<\/p>/, hero, 'heroSub');
const splatWord = pick(/<title>([^<]+)<\/title>/, refHtml, 'title').split('\u00b7')[1].trim();

const out = [];
out.push('<template>');
out.push('  <!-- login page: original light scene + ' + splatWord + ' truck (SplatTruck light theme) + water ripple -->');
out.push('  <main class="login-page">');
out.push('    <div class="sky"></div>');
out.push('    <div class="beams"><i></i><i></i><i></i></div>');
out.push('');
out.push('    <ClientOnly><SplatTruck class="splat-layer" theme="light" :shift-x="-0.19" :shift-y="-0.13" :size="1.3" :depth="0" :drift="0" :auto-spin="false" /></ClientOnly>');
out.push('    <ClientOnly><WaterRipple /></ClientOnly>');
out.push('');
out.push('    <header class="top">');
out.push('      <div class="brand">');
out.push('        <div class="logo">DST</div>');
out.push('        <div>');
out.push('          <div class="brand-title">{{ t.brandTitle }}</div>');
out.push('          <div class="brand-sub">DST IOT INTELLIGENT PLATFORM</div>');
out.push('        </div>');
out.push('      </div>');
out.push('    </header>');
out.push('');
out.push('    <section class="form-side">');
out.push('      <form class="login" @submit.prevent="onSubmit">');
out.push('        <svg class="card-shield" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><path d="M12 3 5 6v5c0 4.6 2.9 8 7 10 4.1-2 7-5.4 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-4"/></svg>');
out.push('        <h2>{{ t.welcome }}</h2>');
out.push('        <p class="sub">{{ t.sub }}</p>');
out.push('        <p class="platform-tag">INTELLIGENT MOBILITY PLATFORM</p>');
out.push('        <label class="field">');
out.push('          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><circle cx="12" cy="8" r="4"/><path d="M5 21v-2a7 7 0 0 1 14 0v2"/></svg>');
out.push('          <input v-model.trim="username" aria-label="account" :placeholder="t.account" autocomplete="username" />');
out.push('        </label>');
out.push('        <label class="field">');
out.push('          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg>');
out.push('          <input v-model="password" :type="showPwd ? \'text\' : \'password\'" aria-label="password" :placeholder="t.password" autocomplete="current-password" />');
out.push('          <button class="eye" type="button" :aria-label="showPwd ? \'hide\' : \'show\'" @click="showPwd = !showPwd"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" style="width:18px;height:18px"><path d="M2 12s3.5-6.5 10-6.5S22 12 22 12s-3.5 6.5-10 6.5S2 12 22 12z"/><circle cx="12" cy="12" r="2.5"/></svg></button>');
out.push('        </label>');
out.push('        <div class="row">');
out.push('          <label class="check"><input v-model="remember" type="checkbox" />{{ t.remember }}</label>');
out.push('          <a class="link" href="#" @click.prevent>{{ t.forgot }}</a>');
out.push('        </div>');
out.push('        <p v-if="error" class="err">{{ error }}</p>');
out.push('        <button class="submit" type="submit" :disabled="loading">{{ loading ? stageText : t.login }}<span class="btn-arrow" aria-hidden="true">&#8594;</span></button>');
out.push('        <div class="or">{{ t.orNote }}</div>');
out.push('        <div class="signup">admin / admin123 &middot; op1 / op123456</div>');
out.push('      </form>');
out.push('    </section>');
out.push('');
out.push('    <div class="hero-copy">');
out.push('      <h1>' + heroTitle1 + '<br><em>' + heroTitle2 + '</em></h1>');
out.push('      <p>{{ t.heroDesc }}</p>');
out.push('    </div>');
out.push('');
out.push('    <span class="corner-tag">DST IOT INTELLIGENT PLATFORM</span>');
out.push('  </main>');
out.push('</template>');
out.push('');
out.push('<script setup>');
out.push("definePageMeta({ layout: false })");
out.push('');
out.push("const { login } = useAuth()");
out.push("const username = ref('admin')");
out.push("const password = ref('admin123')");
out.push('const remember = ref(true)');
out.push('const showPwd = ref(false)');
out.push('const loading = ref(false)');
out.push("const stageText = ref('')");
out.push("const error = ref('')");
out.push('');
out.push('const t = {');
out.push("  brandTitle: '" + brandTitle + "',");
out.push("  welcome: '" + welcome + "',");
out.push("  sub: '" + sub + "',");
out.push("  account: '" + account + "',");
out.push("  password: '" + passwordPh + "',");
out.push("  remember: '" + remember + "',");
out.push("  forgot: '" + forgot + "',");
out.push("  login: '" + loginBtn + "',");
out.push("  orNote: '" + orNote + "',");
out.push("  heroDesc: '" + heroSub + "'");
out.push('}');
out.push('');
out.push('async function onSubmit() {');
out.push('  if (!username.value || !password.value || loading.value) return');
out.push('  loading.value = true');
out.push("  error.value = ''");
out.push("  stageText.value = '" + verifying + "'");
out.push('  try {');
out.push('    const res = await login(username.value, password.value)');
out.push('    if (res.ok) {');
out.push('      ' + navComment);
out.push("      navigateTo('/transition')");
out.push('    } else {');
out.push("      error.value = res.message || '" + badCred + "'");
out.push('    }');
out.push('  } catch (e) {');
out.push("    error.value = '" + netErr + "'");
out.push('  } finally {');
out.push('    loading.value = false');
out.push('  }');
out.push('}');
out.push('</' + 'script>');
out.push('');
out.push('<style scoped>');
out.push('.login-page {');
out.push('  position: fixed; inset: 0; overflow: hidden;');
out.push('  background: #C6DEE3; color: #12403E;');
out.push('}');
out.push('');
out.push('/* ===== sky ===== */');
out.push('.sky {');
out.push('  position: absolute; inset: 0; z-index: 0;');
out.push('  background:');
out.push('    radial-gradient(900px 480px at 30% 18%, rgba(255, 255, 255, 0.55), transparent 60%),');
out.push('    radial-gradient(700px 420px at 78% 30%, rgba(43, 191, 175, 0.10), transparent 65%),');
out.push('    linear-gradient(180deg, #E6F2F5 0%, #CFE4E9 46%, #B7D6DD 72%, #A5CBD4 100%);');
out.push('}');
out.push('.beams { position: absolute; inset: 0; z-index: 1; overflow: hidden; pointer-events: none; }');
out.push('.beams i {');
out.push('  position: absolute; top: -30%; width: 220px; height: 160%;');
out.push('  background: linear-gradient(180deg, rgba(255, 255, 255, 0.35), rgba(255, 255, 255, 0));');
out.push('  transform: rotate(18deg); filter: blur(28px); opacity: .5;');
out.push('  animation: beam-drift 14s ease-in-out infinite;');
out.push('}');
out.push('.beams i:nth-child(1) { left: 12%; }');
out.push('.beams i:nth-child(2) { left: 44%; animation-delay: -5s; opacity: .35; }');
out.push('.beams i:nth-child(3) { left: 74%; animation-delay: -9s; opacity: .28; }');
out.push('@keyframes beam-drift {');
out.push('  0%, 100% { transform: rotate(18deg) translateX(0); }');
out.push('  50% { transform: rotate(18deg) translateX(46px); }');
out.push('}');
out.push('');
out.push('/* ===== splat truck layer (replaces static hero image) ===== */');
out.push('.splat-layer { z-index: 3; }');
out.push('');
out.push('/* ===== header ===== */');
out.push('.top {');
out.push('  position: absolute; top: 0; left: 0; right: 0; z-index: 6;');
out.push('  display: flex; align-items: center; justify-content: space-between;');
out.push('  padding: 22px 36px;');
out.push('}');
out.push('.brand { display: flex; align-items: center; gap: 12px; }');
out.push('.logo {');
out.push('  font-size: 26px; font-weight: 800; font-style: italic; letter-spacing: 1px;');
out.push('  background: linear-gradient(135deg, #0E8A8A, #2BBFAF);');
out.push('  -webkit-background-clip: text; background-clip: text; color: transparent;');
out.push('}');
out.push('.brand-title { font-size: 15px; font-weight: 700; color: #12403E; }');
out.push('.brand-sub { font-size: 10px; letter-spacing: 2px; color: rgba(18, 64, 62, 0.45); }');
out.push('');
out.push('/* ===== floating form ===== */');
out.push('.form-side {');
out.push('  position: absolute; right: 4.5%; top: 50%; transform: translateY(-50%); z-index: 5;');
out.push('  width: min(400px, 92vw);');
out.push('  display: flex; align-items: center; justify-content: center;');
out.push('}');
out.push('.login {');
out.push('  width: 100%; padding: 38px 34px 30px;');
out.push('  background: rgba(255, 255, 255, 0.55); backdrop-filter: blur(20px);');
out.push('  border: 1px solid rgba(255, 255, 255, 0.65); border-radius: 22px;');
out.push('  box-shadow: 0 18px 50px rgba(18, 64, 62, 0.16);');
out.push('  text-align: center;');
out.push('}');
out.push('.card-shield { width: 40px; height: 40px; color: #0E8A8A; margin-bottom: 10px; }');
out.push('.login h2 { margin: 0; font-size: 24px; font-weight: 800; color: #12403E; }');
out.push('.login .sub { margin: 8px 0 2px; font-size: 13px; color: rgba(18, 64, 62, 0.55); }');
out.push('.platform-tag { margin: 0 0 22px; font-size: 10px; letter-spacing: 2.5px; color: rgba(18, 64, 62, 0.35); }');
out.push('');
out.push('.field {');
out.push('  display: flex; align-items: center; gap: 10px;');
out.push('  margin-bottom: 14px; padding: 0 14px; height: 46px;');
out.push('  background: rgba(255, 255, 255, 0.78);');
out.push('  border: 1px solid rgba(14, 138, 138, 0.16); border-radius: 12px;');
out.push('  transition: border-color .15s ease, box-shadow .15s ease;');
out.push('}');
out.push('.field:focus-within { border-color: #0E8A8A; box-shadow: 0 0 0 3px rgba(14, 138, 138, 0.12); }');
out.push('.field svg { width: 19px; height: 19px; color: rgba(18, 64, 62, 0.45); flex-shrink: 0; }');
out.push('.field input { flex: 1; border: none; outline: none; background: transparent; font-size: 14px; color: #12403E; }');
out.push('.field input::placeholder { color: rgba(18, 64, 62, 0.35); }');
out.push('.eye { border: none; background: none; cursor: pointer; color: rgba(18, 64, 62, 0.45); padding: 2px; }');
out.push('');
out.push('.row {');
out.push('  display: flex; align-items: center; justify-content: space-between;');
out.push('  margin: 4px 2px 16px; font-size: 12px; color: rgba(18, 64, 62, 0.6);');
out.push('}');
out.push('.check { display: flex; align-items: center; gap: 6px; cursor: pointer; }');
out.push('.check input { accent-color: #0E8A8A; }');
out.push('.link { color: #0E8A8A; text-decoration: none; }');
out.push('');
out.push('.err {');
out.push('  margin: 0 0 12px; padding: 8px 12px; font-size: 12px; text-align: left;');
out.push('  color: #B3402E; background: rgba(179, 64, 46, 0.08); border-radius: 8px;');
out.push('}');
out.push('');
out.push('.submit {');
out.push('  width: 100%; height: 46px; border: none; border-radius: 12px; cursor: pointer;');
out.push('  display: flex; align-items: center; justify-content: center; gap: 8px;');
out.push('  background: linear-gradient(135deg, #0E8A8A, #2BBFAF); color: #fff;');
out.push('  font-size: 15px; font-weight: 700; letter-spacing: 2px;');
out.push('  box-shadow: 0 10px 24px rgba(14, 138, 138, 0.35);');
out.push('  transition: transform .15s ease, box-shadow .15s ease;');
out.push('}');
out.push('.submit:hover:not(:disabled) { transform: translateY(-1px); box-shadow: 0 14px 30px rgba(14, 138, 138, 0.45); }');
out.push('.submit:disabled { opacity: 0.75; cursor: default; }');
out.push('.btn-arrow { font-size: 17px; letter-spacing: 0; }');
out.push('');
out.push('.or { margin: 18px 0 6px; font-size: 12px; color: rgba(18, 64, 62, 0.4); }');
out.push('.signup { font-size: 11px; color: rgba(18, 64, 62, 0.45); }');
out.push('');
out.push('.hero-copy { position: absolute; left: 6%; bottom: 6%; z-index: 4; pointer-events: none; }');
out.push('.hero-copy h1 {');
out.push('  margin: 0; font-size: 42px; line-height: 1.25; font-weight: 800; color: #12403E;');
out.push('  text-shadow: 0 2px 18px rgba(255, 255, 255, 0.85);');
out.push('}');
out.push('.hero-copy h1 em { font-style: normal; color: #0E8A8A; }');
out.push('.hero-copy p { margin: 12px 0 0; font-size: 15px; color: rgba(18, 64, 62, 0.62); max-width: 420px; }');
out.push('');
out.push('.corner-tag {');
out.push('  position: absolute; left: 24px; bottom: 16px; z-index: 6;');
out.push('  font-size: 10px; letter-spacing: 3px; color: rgba(18, 64, 62, 0.45);');
out.push('}');
out.push('');
out.push('@media (max-width: 900px) {');
out.push('  .splat-layer { opacity: .55; }');
out.push('  .form-side { right: 50%; transform: translate(50%, -50%); }');
out.push('}');
out.push('</style>');
out.push('');

const target = root + '/pages/login.vue';
fs.writeFileSync(target, out.join('\n'), 'utf8');
console.log('written', target, out.length, 'lines');
