// Generator: build SplatTruck.vue from reference HTML (shaders extracted at runtime)
const fs = require('fs');
const html = fs.readFileSync('E:/dst_agent_car/index (7).html', 'utf8');
const BT = String.fromCharCode(96);

function grab(startMark, endMark) {
  const i = html.indexOf(startMark);
  if (i < 0) throw new Error('missing: ' + startMark);
  const j = html.indexOf(endMark, i + startMark.length);
  if (j < 0) throw new Error('missing end for: ' + startMark);
  return html.slice(i + startMark.length, j);
}

// grab a full line containing the anchor (Chinese comments sourced from reference file)
function lineGrab(anchor) {
  const i = html.indexOf(anchor);
  if (i < 0) throw new Error('anchor missing: ' + anchor);
  let s = html.lastIndexOf('\n', i) + 1;
  let e = html.indexOf('\n', i);
  if (e < 0) e = html.length;
  return html.slice(s, e).trim();
}

let vert = grab('const VERT = ' + BT, BT + ';');
let frag = grab('const FRAG = ' + BT, BT + ';');

// inject scene-shift uniform (used by login layout to offset the truck)
vert = vert.replace(
  'uniform vec2  u_res;',
  'uniform vec2  u_res;\nuniform vec2  u_shift;   // scene offset in pixels'
);
vert = vert.replace(
  'p = u_rot * p;',
  'p.xy += u_shift;\n  p = u_rot * p;'
);
if (vert.indexOf('u_shift') < 0) throw new Error('u_shift patch failed');

// Chinese comments reused verbatim from the reference file
const zhSplat = lineGrab('splat');        // e.g. 2.5D Gaussian Splatting holo deck intro
const zhFx = lineGrab('FX');              // fx layer comment line
const zhVbo = lineGrab('VBO');            // upload splat buffers comment
const zhImg = lineGrab('buildSplats');    // image sampling comment
const zhFxBuild = lineGrab('buildFx');    // fx build comment
const zhMouse = lineGrab('mouse');        // interaction comment
const zhFrame = lineGrab('frame');        // main loop comment

const out = [];
out.push('<template>');
out.push('  <!-- Gaussian splatting holo truck: image -> pixel sampling -> 2.5D splat cloud -->');
out.push('  <!-- ' + zhFx + ' -->');
out.push('  <div ref="wrap" class="splat-truck">');
out.push('    <canvas ref="cv" :class="{ show: ready }" @pointerdown="onPulse"></canvas>');
out.push('    <div v-if="!ready" class="veil">');
out.push('      <div class="bar"><i></i></div>');
out.push('      <p>INITIALIZING SPLATS</p>');
out.push('    </div>');
out.push('  </div>');
out.push('</template>');
out.push('');
out.push('<script setup>');
out.push('// 2.5D Gaussian Splatting holo deck, ported from E:/dst_agent_car reference');
out.push('// ' + zhSplat);
out.push('const props = defineProps({');
out.push("  src: { type: String, default: '/images/splat-truck.png' },");
out.push('  density: { type: Number, default: 2 },   // sampling step in px, smaller = denser');
out.push('  size: { type: Number, default: 2.4 },    // splat radius factor');
out.push('  depth: { type: Number, default: 1.0 },   // z-depth factor');
out.push('  drift: { type: Number, default: 1.0 },   // breathing drift amplitude');
out.push('  shiftX: { type: Number, default: 0 },    // scene offset x, fraction of view width (negative = left)');
out.push('  shiftY: { type: Number, default: 0 },    // scene offset y, fraction of view height (positive = up)');
out.push('  autoSpin: { type: Boolean, default: true }');
out.push('})');
out.push("const emit = defineEmits(['ready'])");
out.push('');
out.push('const wrap = ref(null)');
out.push('const cv = ref(null)');
out.push('const ready = ref(false)');
out.push('');
out.push('let gl = null');
out.push('let prog = null');
out.push('let A = null');
out.push('let U = null');
out.push('let imgBufs = null');
out.push('let fxBufs = null');
out.push('let splatCount = 0');
out.push('let fxCount = 0');
out.push('let truckW = 0');
out.push('let truckH = 0');
out.push('let truckScale = 1');
out.push('let rafId = null');
out.push('let disposed = false');
out.push('let ro = null');
out.push('');
out.push('// ' + zhMouse);
out.push('const mouse = { x: 0, y: 0, tx: 0, ty: 0, k: 0, tk: 0 }');
out.push('const rot = { yaw: 0, pitch: 0 }');
out.push('let pulse = 0');
out.push('let scatter = 1.0           // start scattered, assemble on load');
out.push('const scatterTarget = 0');
out.push('');
out.push('// ---- shaders ----');
out.push('const VERT = ' + BT + vert + BT);
out.push('');
out.push('const FRAG = ' + BT + frag + BT);
out.push('');
out.push('function compile(type, src) {');
out.push('  const s = gl.createShader(type)');
out.push('  gl.shaderSource(s, src)');
out.push('  gl.compileShader(s)');
out.push('  if (!gl.getShaderParameter(s, gl.COMPILE_STATUS)) throw new Error(gl.getShaderInfoLog(s))');
out.push('  return s');
out.push('}');
out.push('');
out.push('// ' + zhVbo);
out.push('function makeVBO(set) {');
out.push('  const make = (loc, arr, comps) => {');
out.push('    const buf = gl.createBuffer()');
out.push('    gl.bindBuffer(gl.ARRAY_BUFFER, buf)');
out.push('    gl.bufferData(gl.ARRAY_BUFFER, arr, gl.STATIC_DRAW)');
out.push('    return { buf, loc, comps }');
out.push('  }');
out.push('  return {');
out.push('    home: make(A.home, set.home, 3),');
out.push('    color: make(A.color, set.color, 4),');
out.push('    size: make(A.size, set.size, 1),');
out.push('    seed: make(A.seed, set.seed, 1),');
out.push('    kind: set.kind ? make(A.kind, set.kind, 1) : null');
out.push('  }');
out.push('}');
out.push('');
out.push('function bindVBO(bufs) {');
out.push('  for (const b of Object.values(bufs)) {');
out.push('    if (!b) continue');
out.push('    gl.bindBuffer(gl.ARRAY_BUFFER, b.buf)');
out.push('    gl.enableVertexAttribArray(b.loc)');
out.push('    gl.vertexAttribPointer(b.loc, b.comps, gl.FLOAT, false, 0, 0)');
out.push('  }');
out.push('  if (!bufs.kind) {');
out.push('    gl.disableVertexAttribArray(A.kind)');
out.push('    gl.vertexAttrib1f(A.kind, 0.0)');
out.push('  }');
out.push('}');
out.push('');
out.push('function dropVBO(bufs) {');
out.push('  if (bufs) for (const b of Object.values(bufs)) if (b) gl.deleteBuffer(b.buf)');
out.push('}');
out.push('');
out.push('// ' + zhImg + ' (sorted far-to-near, painter algorithm)');
out.push('function buildSplats(img, step, vw, vh) {');
out.push('  const w = img.width');
out.push('  const h = img.height');
out.push("  const off = document.createElement('canvas')");
out.push('  off.width = w');
out.push('  off.height = h');
out.push("  const ctx = off.getContext('2d', { willReadFrequently: true })");
out.push('  ctx.drawImage(img, 0, 0)');
out.push('  const data = ctx.getImageData(0, 0, w, h).data');
out.push('');
out.push('  let hasAlpha = false');
out.push('  for (let i = 3; i < data.length; i += 16) if (data[i] < 250) { hasAlpha = true; break }');
out.push('');
out.push('  const keep = (i) => {');
out.push('    if (hasAlpha) return data[i + 3] > 140');
out.push('    const r = data[i]; const g = data[i + 1]; const b = data[i + 2]');
out.push('    const lum = (r * 0.2126 + g * 0.7152 + b * 0.0722) / 255');
out.push('    const sat = (Math.max(r, g, b) - Math.min(r, g, b)) / 255');
out.push('    return lum < 0.90 || sat > 0.13');
out.push('  }');
out.push('');
out.push('  let n = 0');
out.push('  for (let y = 0; y < h; y += step)');
out.push('    for (let x = 0; x < w; x += step)');
out.push('      if (keep((y * w + x) * 4)) n++');
out.push('');
out.push('  const home = new Float32Array(n * 3)');
out.push('  const color = new Float32Array(n * 4)');
out.push('  const size = new Float32Array(n)');
out.push('  const seed = new Float32Array(n)');
out.push('');
out.push('  truckW = w');
out.push('  truckH = h');
out.push('  truckScale = Math.min((vw * 0.62) / w, (vh * 0.72) / h)');
out.push('  const scale = truckScale');
out.push('');
out.push('  let k = 0');
out.push('  for (let y = 0; y < h; y += step) {');
out.push('    for (let x = 0; x < w; x += step) {');
out.push('      const i = (y * w + x) * 4');
out.push('      if (!keep(i)) continue');
out.push('      const r = data[i]; const g = data[i + 1]; const b = data[i + 2]');
out.push('      const lum = (r * 0.2126 + g * 0.7152 + b * 0.0722) / 255');
out.push('      const sat = (Math.max(r, g, b) - Math.min(r, g, b)) / 255');
out.push('');
out.push('      const jx = (Math.random() - 0.5) * step * 0.9');
out.push('      const jy = (Math.random() - 0.5) * step * 0.9');
out.push('');
out.push('      home[k * 3] = (x + jx - w / 2) * scale');
out.push('      home[k * 3 + 1] = (h / 2 - y - jy) * scale');
out.push('      home[k * 3 + 2] = (0.5 - lum) * 260.0 + (Math.random() - 0.5) * 24.0');
out.push('');
out.push('      color[k * 4] = r / 255');
out.push('      color[k * 4 + 1] = g / 255');
out.push('      color[k * 4 + 2] = b / 255');
out.push('      let alpha = Math.min(1, 0.84 + (1 - lum) * 0.25 + sat * 0.20)');
out.push('      if (hasAlpha) {');
out.push('        alpha *= Math.min(1, data[i + 3] / 200)');
out.push('      } else {');
out.push('        const fx = Math.min(x, w - x) / w');
out.push('        const fy = Math.min(y, h - y) / h');
out.push('        alpha *= Math.min(1, Math.min(fx, fy) / 0.035)');
out.push('      }');
out.push('      color[k * 4 + 3] = alpha');
out.push('');
out.push('      size[k] = step * scale * (1.8 + Math.random() * 0.5)');
out.push('      seed[k] = Math.random()');
out.push('      k++');
out.push('    }');
out.push('  }');
out.push('');
out.push('  const order = Array.from({ length: n }, (_, i) => i)');
out.push('  order.sort((a2, b2) => home[b2 * 3 + 2] - home[a2 * 3 + 2])');
out.push('');
out.push('  const sHome = new Float32Array(n * 3)');
out.push('  const sColor = new Float32Array(n * 4)');
out.push('  const sSize = new Float32Array(n)');
out.push('  const sSeed = new Float32Array(n)');
out.push('  for (let m = 0; m < n; m++) {');
out.push('    const s = order[m]');
out.push('    sHome.set(home.subarray(s * 3, s * 3 + 3), m * 3)');
out.push('    sColor.set(color.subarray(s * 4, s * 4 + 4), m * 4)');
out.push('    sSize[m] = size[s]');
out.push('    sSeed[m] = seed[s]');
out.push('  }');
out.push('  return { n, home: sHome, color: sColor, size: sSize, seed: sSeed }');
out.push('}');
out.push('');
out.push('// ' + zhFxBuild);
out.push('function buildFx() {');
out.push('  const halfW = (truckW * truckScale) / 2');
out.push('  const halfH = (truckH * truckScale) / 2');
out.push('  const baseY = -halfH * 0.94');
out.push('  const R1 = halfW * 0.86');
out.push('  const R2 = halfW * 0.62');
out.push('  const RO = halfW * 0.78');
out.push('');
out.push('  const N_GROUND = 900');
out.push('  const N_ORBIT = 520');
out.push('  const N_DUST = 850');
out.push('  const n = N_GROUND + N_ORBIT + N_DUST');
out.push('');
out.push('  const home = new Float32Array(n * 3)');
out.push('  const color = new Float32Array(n * 4)');
out.push('  const size = new Float32Array(n)');
out.push('  const seed = new Float32Array(n)');
out.push('  const kind = new Float32Array(n)');
out.push('');
out.push('  let k = 0');
out.push('  const push = (hx, hy, hz, r, g, b, a, sz, kd) => {');
out.push('    home[k * 3] = hx; home[k * 3 + 1] = hy; home[k * 3 + 2] = hz');
out.push('    color[k * 4] = r; color[k * 4 + 1] = g; color[k * 4 + 2] = b; color[k * 4 + 3] = a');
out.push('    size[k] = sz; seed[k] = Math.random(); kind[k] = kd');
out.push('    k++');
out.push('  }');
out.push('');
out.push('  for (let i = 0; i < N_GROUND; i++) {');
out.push('    const inner = i < N_GROUND * 0.55');
out.push('    const R = (inner ? R2 : R1) * (0.985 + Math.random() * 0.03)');
out.push('    push(R, baseY, Math.random() * Math.PI * 2,');
out.push('      0.30, 0.95, 0.88, inner ? 0.34 : 0.5,');
out.push('      (inner ? 2.2 : 2.8) + Math.random() * 1.4, 1)');
out.push('    if (inner) seed[k - 1] = Math.random() * 0.5');
out.push('    else seed[k - 1] = 0.5 + Math.random() * 0.5');
out.push('  }');
out.push('  for (let i = 0; i < N_ORBIT; i++) {');
out.push('    const R = RO * (0.99 + Math.random() * 0.02)');
out.push('    push(R, halfH * 0.10, Math.random() * Math.PI * 2,');
out.push('      0.42, 0.98, 0.92, 0.42,');
out.push('      1.6 + Math.random() * 1.2, 2)');
out.push('  }');
out.push('  for (let i = 0; i < N_DUST; i++) {');
out.push('    push((Math.random() - 0.5) * halfW * 2.6,');
out.push('      (Math.random() - 0.5) * halfH * 2.6,');
out.push('      (Math.random() - 0.5) * 500,');
out.push('      0.45, 0.95, 0.90, 0.10 + Math.random() * 0.22,');
out.push('      1.2 + Math.random() * 2.0, 3)');
out.push('  }');
out.push('  return { n, home, color, size, seed, kind }');
out.push('}');
out.push('');
out.push('function onPulse() { pulse = 1.0 }');
out.push('');
out.push('function onPointerMove(e) {');
out.push('  if (!wrap.value) return');
out.push('  const r = wrap.value.getBoundingClientRect()');
out.push('  mouse.tx = e.clientX - r.left - r.width / 2');
out.push('  mouse.ty = r.height / 2 - (e.clientY - r.top)');
out.push('  mouse.tk = 26');
out.push('}');
out.push('function onPointerLeave() { mouse.tk = 0 }');
out.push('');
out.push('// ' + zhFrame);
out.push('let lastT = 0');
out.push('function frame(now) {');
out.push('  if (disposed) return');
out.push('  lastT = now');
out.push('  const t = now / 1000');
out.push('  const rect = wrap.value.getBoundingClientRect()');
out.push('  const vw = rect.width');
out.push('  const vh = rect.height');
out.push('');
out.push('  scatter += (scatterTarget - scatter) * 0.045');
out.push('  pulse *= 0.94');
out.push('  const sEff = Math.min(scatter + pulse * 0.85, 1.4)');
out.push('');
out.push('  mouse.x += (mouse.tx - mouse.x) * 0.06');
out.push('  mouse.y += (mouse.ty - mouse.y) * 0.06');
out.push('  mouse.k += (mouse.tk - mouse.k) * 0.08');
out.push('');
out.push('  const targetYaw = props.autoSpin ? Math.sin(t * 0.22) * 0.42 : (mouse.x / vw) * 0.34');
out.push('  const targetPitch = (mouse.y / vh) * -0.22');
out.push('  rot.yaw += (targetYaw - rot.yaw) * 0.05');
out.push('  rot.pitch += (targetPitch - rot.pitch) * 0.05');
out.push('');
out.push('  const cy = Math.cos(rot.yaw); const sy = Math.sin(rot.yaw)');
out.push('  const cp = Math.cos(rot.pitch); const sp = Math.sin(rot.pitch)');
out.push('  const m = new Float32Array([');
out.push('    cy, 0, -sy,');
out.push('    sy * sp, cp, cy * sp,');
out.push('    sy * cp, -sp, cy * cp');
out.push('  ])');
out.push('');
out.push('  gl.clear(gl.COLOR_BUFFER_BIT)');
out.push('  gl.uniform1f(U.u_time, t)');
out.push('  gl.uniformMatrix3fv(U.u_rot, false, m)');
out.push('  gl.uniform2f(U.u_mouse, mouse.x, mouse.y)');
out.push('  gl.uniform1f(U.u_mouseK, mouse.k)');
out.push('  gl.uniform1f(U.u_scatter, sEff)');
out.push('  gl.uniform1f(U.u_depth, props.depth)');
out.push('  gl.uniform1f(U.u_drift, props.drift)');
out.push('  gl.uniform1f(U.u_sizeK, props.size / 2.4)');
out.push('  gl.uniform2f(U.u_shift, props.shiftX * vw, props.shiftY * vh)');
out.push('');
out.push('  // image layer: normal alpha blend; fx layer: additive glow');
out.push('  gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA)');
out.push('  if (imgBufs) { bindVBO(imgBufs); gl.drawArrays(gl.POINTS, 0, splatCount) }');
out.push('  gl.blendFunc(gl.SRC_ALPHA, gl.ONE)');
out.push('  if (fxBufs) { bindVBO(fxBufs); gl.drawArrays(gl.POINTS, 0, fxCount) }');
out.push('');
out.push('  rafId = requestAnimationFrame(frame)');
out.push('}');
out.push('');
out.push('function resize() {');
out.push('  if (!gl || !wrap.value) return');
out.push('  const rect = wrap.value.getBoundingClientRect()');
out.push('  const dpr = Math.min(window.devicePixelRatio || 1, 2)');
out.push('  cv.value.width = Math.max(1, rect.width * dpr)');
out.push('  cv.value.height = Math.max(1, rect.height * dpr)');
out.push('  gl.viewport(0, 0, cv.value.width, cv.value.height)');
out.push('  gl.uniform2f(U.u_res, rect.width, rect.height)');
out.push('  gl.uniform1f(U.u_dpr, dpr)');
out.push('}');
out.push('');
out.push('let srcImg = null');
out.push('function rebuild() {');
out.push('  if (!srcImg || !wrap.value) return');
out.push('  const rect = wrap.value.getBoundingClientRect()');
out.push('  dropVBO(imgBufs); dropVBO(fxBufs)');
out.push('  const s = buildSplats(srcImg, props.density, rect.width, rect.height)');
out.push('  imgBufs = makeVBO(s)');
out.push('  splatCount = s.n');
out.push('  const fx = buildFx()');
out.push('  fxBufs = makeVBO(fx)');
out.push('  fxCount = fx.n');
out.push('}');
out.push('');
out.push('let resizeTimer = 0');
out.push('function onResize() {');
out.push('  resize()');
out.push('  clearTimeout(resizeTimer)');
out.push('  resizeTimer = setTimeout(rebuild, 260)');
out.push('}');
out.push('');
out.push('onMounted(() => {');
out.push('  const canvas = cv.value');
out.push("  gl = canvas.getContext('webgl', { alpha: false, antialias: false, powerPreference: 'high-performance' })");
out.push('  if (!gl) {');
out.push('    ready.value = true');
out.push("    emit('ready')");
out.push('    return');
out.push('  }');
out.push('');
out.push('  prog = gl.createProgram()');
out.push('  gl.attachShader(prog, compile(gl.VERTEX_SHADER, VERT))');
out.push('  gl.attachShader(prog, compile(gl.FRAGMENT_SHADER, FRAG))');
out.push('  gl.linkProgram(prog)');
out.push('  if (!gl.getProgramParameter(prog, gl.LINK_STATUS)) throw new Error(gl.getProgramInfoLog(prog))');
out.push('  gl.useProgram(prog)');
out.push('');
out.push('  A = {');
out.push("    home: gl.getAttribLocation(prog, 'a_home'),");
out.push("    color: gl.getAttribLocation(prog, 'a_color'),");
out.push("    size: gl.getAttribLocation(prog, 'a_size'),");
out.push("    seed: gl.getAttribLocation(prog, 'a_seed'),");
out.push("    kind: gl.getAttribLocation(prog, 'a_kind')");
out.push('  }');
out.push('  U = {}');
out.push("  for (const n of ['u_res', 'u_shift', 'u_time', 'u_rot', 'u_mouse', 'u_mouseK', 'u_scatter', 'u_depth', 'u_drift', 'u_sizeK', 'u_dpr'])");
out.push('    U[n] = gl.getUniformLocation(prog, n)');
out.push('');
out.push('  gl.disable(gl.DEPTH_TEST)');
out.push('  gl.clearColor(0.008, 0.075, 0.086, 1.0)   // deep tech background');
out.push('');
out.push("  window.addEventListener('pointermove', onPointerMove)");
out.push("  window.addEventListener('pointerleave', onPointerLeave)");
out.push("  window.addEventListener('resize', onResize)");
out.push('  if (window.ResizeObserver) {');
out.push('    ro = new ResizeObserver(onResize)');
out.push('    ro.observe(wrap.value)');
out.push('  }');
out.push('');
out.push('  const img = new Image()');
out.push('  img.onload = () => {');
out.push('    if (disposed) return');
out.push('    srcImg = img');
out.push('    resize()');
out.push('    rebuild()');
out.push('    lastT = performance.now()');
out.push('    rafId = requestAnimationFrame(frame)');
out.push("    setTimeout(() => { ready.value = true; emit('ready') }, 350)");
out.push('  }');
out.push("  img.onerror = () => { ready.value = true; emit('ready') }");
out.push('  img.src = props.src');
out.push('})');
out.push('');
out.push('onBeforeUnmount(() => {');
out.push('  disposed = true');
out.push('  if (rafId) cancelAnimationFrame(rafId)');
out.push('  clearTimeout(resizeTimer)');
out.push("  window.removeEventListener('pointermove', onPointerMove)");
out.push("  window.removeEventListener('pointerleave', onPointerLeave)");
out.push("  window.removeEventListener('resize', onResize)");
out.push('  if (ro) ro.disconnect()');
out.push('  dropVBO(imgBufs); dropVBO(fxBufs)');
out.push('  if (gl) {');
out.push("    const ext = gl.getExtension('WEBGL_lose_context')");
out.push('    if (ext) ext.loseContext()');
out.push('  }');
out.push('})');
out.push('</' + 'script>');
out.push('');
out.push('<style scoped>');
out.push('.splat-truck { position: absolute; inset: 0; overflow: hidden; }');
out.push('.splat-truck canvas {');
out.push('  position: absolute; inset: 0; width: 100%; height: 100%;');
out.push('  display: block; cursor: crosshair;');
out.push('  opacity: 0;');
out.push('  transition: opacity .8s ease;');
out.push('}');
out.push('.splat-truck canvas.show { opacity: 1; }');
out.push('/* loading veil */');
out.push('.veil {');
out.push('  position: absolute; inset: 0; z-index: 5;');
out.push('  display: flex; align-items: center; justify-content: center;');
out.push('  flex-direction: column; gap: 18px; pointer-events: none;');
out.push('}');
out.push('.veil .bar { width: 200px; height: 2px; background: rgba(64, 232, 220, .14); overflow: hidden; }');
out.push('.veil .bar i {');
out.push('  display: block; height: 100%; width: 40%;');
out.push('  background: #40e8dc; box-shadow: 0 0 10px #40e8dc;');
out.push('  animation: scan 1.1s ease-in-out infinite alternate;');
out.push('}');
out.push('@keyframes scan { from { transform: translateX(-60%); } to { transform: translateX(320%); } }');
out.push('.veil p {');
out.push('  margin: 0; font-size: 11px; letter-spacing: .34em; color: #7fc9c6;');
out.push('  font-family: ui-monospace, "SF Mono", "JetBrains Mono", Menlo, Consolas, monospace;');
out.push('}');
out.push('</style>');
out.push('');

const target = 'D:/code/work-space-agent/dst-v2x-agent/frontend/components/login/SplatTruck.vue';
fs.writeFileSync(target, out.join('\n'), 'utf8');
console.log('written', target, out.length, 'lines');
